name: openpack-actions
version: v3.2.1
path:
  dir: ${path.openpack.rootdir}/${user.name}/annotation/${..name}
  fname: ${session}.csv
file_format:
  file_type: csv
  columns:
  - name: unixtime
    unit: milli scond
  - name: user
  - name: session
  - name: box
  - name: operation
  - name: action
classes:
- id: 101
  operation: Picking
  name: PickUp-Sheet
  description: ''
  version: v3.0.0
  ignore: false
- id: 102
  operation: Picking
  name: Walk-ToRack
  description: ''
  version: v3.0.0
  ignore: false
- id: 103
  operation: Picking
  name: PickUp-Item-FromBox
  description: ''
  version: v3.0.0
  ignore: false
- id: 104
  operation: Picking
  name: Pick-UpOrderSheet&Walk-ToRack-v2
  description: ''
  version: v2.5.x
  ignore: false
- id: 105
  operation: Picking
  name: Walk-ToWorkBench-v2
  description: ''
  version: v2.5.x
  ignore: false
- id: 106
  operation: Picking
  name: Pick-UpOrderSheet&Walk-ToRack-with-PrevPackedBox-v2
  description: ''
  version: v2.5.x
  ignore: false
- id: 107
  operation: Picking
  name: PickUp-BoxSheet
  description: ''
  version: v3.1.0
  ignore: false
- id: 108
  operation: Picking
  name: Walk-ToWorkBench
  description: ''
  version: v3.2.1
  ignore: false
- id: 201
  operation: RelocateItemLabel
  name: Remove-ItemLabel
  description: ''
  version: v3.0.0
  ignore: false
- id: 202
  operation: RelocateItemLabel
  name: AttachTo-OrderSheet
  description: ''
  version: v3.0.0
  ignore: false
- id: 203
  operation: RelocateItemLabel
  name: Hold-Pen
  description: ''
  version: v3.0.0
  ignore: false
- id: 204
  operation: RelocateItemLabel
  name: Write-CheckMark
  description: ''
  version: v3.2.0
  ignore: false
- id: 205
  operation: RelocateItemLabel
  name: Put-Item-SmallBag
  description: ''
  version: v3.2.0
  ignore: false
- id: 206
  operation: RelocateItemLabel
  name: Relocate-ItemLabel-v2
  description: ''
  version: v2.5.x
  ignore: false
- id: 207
  operation: RelocateItemLabel
  name: Write-v2
  description: ''
  version: v2.5.x
  ignore: false
- id: 301
  operation: AssembleBox
  name: Pick-Cardboard
  description: ''
  version: v3.0.0
  ignore: false
- id: 302
  operation: AssembleBox
  name: Bend-Flap
  description: ''
  version: v3.2.0
  ignore: false
- id: 303
  operation: AssembleBox
  name: Attach-Tape
  description: ''
  version: v3.2.0
  ignore: false
- id: 304
  operation: AssembleBox
  name: TurnOver-Box
  description: ''
  version: v3.2.0
  ignore: false
- id: 305
  operation: AssembleBox
  name: PickUp-AssembledBox
  description: ''
  version: v3.0.0
  ignore: false
- id: 306
  operation: AssembleBox
  name: AssembleBox-v2
  description: ''
  version: v2.5.x
  ignore: false
- id: 401
  operation: InsertItems
  name: Insert-Item-into-Box
  description: ''
  version: v3.0.0
  ignore: false
- id: 402
  operation: InsertItems
  name: AirCushion
  description: ''
  version: v3.0.0
  ignore: false
- id: 403
  operation: InsertItems
  name: Separate-AirCushion
  description: ''
  version: v3.0.0
  ignore: false
- id: 404
  operation: InsertItems
  name: Put-Item-SmallBag
  description: ''
  version: v3.0.0
  ignore: false
- id: 405
  operation: InsertItems
  name: Insert-Items-v2
  description: ''
  version: v2.5.x
  ignore: false
- id: 501
  operation: CloseBox
  name: Bend-Flap
  description: ''
  version: v3.0.0
  ignore: false
- id: 502
  operation: CloseBox
  name: Attach-Tape
  description: ''
  version: v3.0.0
  ignore: false
- id: 503
  operation: CloseBox
  name: CloseBox-v2
  description: ''
  version: v2.5.x
  ignore: false
- id: 601
  operation: AttachBoxLabel
  name: Attach-BoxLabel
  description: ''
  version: v3.2.0
  ignore: false
- id: 602
  operation: AttachBoxLabel
  name: Attach-BoxLabel-v2
  description: ''
  version: v2.5.x
  ignore: false
- id: 701
  operation: ScanLabel
  name: PickUp-HT
  description: ''
  version: v3.0.0
  ignore: false
- id: 702
  operation: ScanLabel
  name: Scan-OrderSheet
  description: ''
  version: v3.2.0
  ignore: false
- id: 703
  operation: ScanLabel
  name: Scan-Box
  description: ''
  version: v3.2.0
  ignore: false
- id: 704
  operation: ScanLabel
  name: Scan-Item
  description: ''
  version: v3.2.0
  ignore: false
- id: 705
  operation: ScanLabel
  name: Hold-Scanner
  description: ''
  version: v3.0.0
  ignore: false
- id: 706
  operation: ScanLabel
  name: Scan-OrderSheet
  description: ''
  version: v3.2.0
  ignore: false
- id: 707
  operation: ScanLabel
  name: Scan-Printer
  description: ''
  version: v3.2.0
  ignore: false
- id: 708
  operation: ScanLabel
  name: HT-v2
  description: ''
  version: v2.5.x
  ignore: false
- id: 709
  operation: ScanLabel
  name: Printer-v2
  description: ''
  version: v2.5.x
  ignore: false
- id: 801
  operation: AttachShippingLabel
  name: PickUp-ShippingLabel
  description: ''
  version: v3.0.0
  ignore: false
- id: 802
  operation: AttachShippingLabel
  name: Attach-ShippingLabel
  description: ''
  version: v3.2.0
  ignore: false
- id: 802
  operation: AttachShippingLabel
  name: Attach-ShippingLabel-v2
  description: ''
  version: v2.5.x
  ignore: false
- id: 901
  operation: PutOnRack
  name: PickUp-PackedBox
  description: ''
  version: v3.0.0
  ignore: false
- id: 902
  operation: PutOnRack
  name: Put-PackedBox
  description: ''
  version: v3.2.0
  ignore: false
- id: 903
  operation: PutOnRack
  name: Put-OnPack-v2
  description: ''
  version: v2.5.x
  ignore: false
- id: 1001
  operation: Fill-outOrder
  name: PickUp-Pen
  description: ''
  version: v3.0.0
  ignore: false
- id: 1002
  operation: Fill-outOrder
  name: Write-Sign
  description: ''
  version: v3.2.0
  ignore: false
- id: 1003
  operation: Fill-outOrder
  name: Push-OrderSheet-IntoTray
  description: ''
  version: v3.2.0
  ignore: false
- id: 1004
  operation: Fill-outOrder
  name: FillOut-v2
  description: ''
  version: v2.5.x
  ignore: false
- id: 1005
  operation: Fill-outOrder
  name: Write-v2
  description: ''
  version: v2.5.x
  ignore: false
- id: 1006
  operation: Fill-outOrder
  name: Insert-v2
  description: ''
  version: v2.5.x
  ignore: false
- id: 8101
  operation: 'Null'
  name: Others
  description: ''
  version: v3.0.0
  ignore: true
- id: 8102
  operation: 'Null'
  name: SystemError
  description: ''
  version: v3.0.0
  ignore: true
- id: 8103
  operation: 'Null'
  name: Ignore
  description: ''
  version: v3.0.0
  ignore: true
- id: 8104
  operation: 'Null'
  name: Unknown
  description: ''
  version: v3.0.0
  ignore: true
- id: 8201
  operation: SystemError
  name: SystemError
  description: ''
  version: v3.0.0
  ignore: true
